---
  - name: Ensure firewalld is installed.
    package: name=firewalld state=installed
  
  - name: Configure the firewalld service
    service:
      name: firewalld
      state: "{{ firewall_state }}"
      enabled: "{{ firewall_enabled_at_boot }}"
  
  - name: Discover zones
    command: firewall-cmd --get-zones
    register: disc_zones
    changed_when: False
  
  - name: Ensure zone exists
    command: "firewall-cmd --new-zone={{firewall_zone}} --permanent && firewall-cmd --reload"
    when: not firewall_zone in disc_zones.stdout.split(' ')
    
  
  # Configure ports to zone
  - name: Discover ports for zone '{{firewall_zone}}'
    command: "firewall-cmd --zone={{firewall_zone}} --list-ports"
    register: zone_ports
    changed_when: False
  
  - name: Discover firewalld managed ports
    set_fact: 
      req_ports: '{{firewall_allowed_tcp_ports|protocolize + firewall_allowed_udp_ports|protocolize("udp")}}'
      enabled_ports: "{{zone_ports.stdout.split(' ')}}"
      
  - name: Ensure requested ports are enabled
    firewalld:
      port: '{{item}}'
      state: enabled
      zone: '{{firewall_zone}}'
    with_items: '{{req_ports}}'
    notify: firewalld make permanent
    
  - name: Ensure not requited ports are not installed
    firewalld:
      port: '{{item}}'
      state: disabled
      zone: '{{firewall_zone}}'
    with_items: '{{enabled_ports|difference(req_ports)}}'
    notify: firewalld make permanent
  # 

    
